apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/iris-web-ui

namePrefix: dev-

patches:
  - target:
      kind: Deployment
      name: iris-web-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
