{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "iris-api-gateway.fullname" . }}-db-secret
  labels:
    {{- include "iris-api-gateway.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "iris-api-gateway.fullname" . }}-db-secret
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRefKey }}
      property: {{ .remoteRefProperty }}
  {{- end }}
{{- end }}
