apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "iris-api-gateway.fullname" . }}
  labels:
    {{- include "iris-api-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "iris-api-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
