{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "postgresql.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefKey }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefKey }}
        property: password
{{- end }}
